spring:
    datasource:
        username: emarket_test
        password: emarket@test@n123
        url: jdbc:mysql://47.98.195.250:3306/emarket_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
    data:
        mongodb:
            first:
                uri: mongodb://47.98.195.250:27017/nidcai-oa
            second:
                uri: mongodb://work:workTest@47.98.195.250:27018/nidcai?authMechanism=SCRAM-SHA-1
mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.nidecai.managerndc.entity
     ##开启驼峰映射
    configuration:
        map-underscore-to-camel-case: true


mapper:
    mappers: tk.mybatis.mapper.common.Mapper
    notEmpty: true
    identity: MYSQL

pagehelper:
    helperDialect:  mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
upload:
    catalogue: /mnt/webData/upload/temp/
    httpCatalogue: /upload/temp/
    maxFileSize: 30720KB
    maxRequestSize: 102400KB